# -*- coding: utf-8 -*-
"""PythonBasic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQuMy9JDreRxa3FjIZP8r8CiqICM_5Ba
"""

2 ** 3

8 / 2

6 * 7.0

2 ** 3

10 // 3

10 % 3

10/3

"""We love python!"""

"We love python!"

"We \"love\" python!"

'Me: Hi, there!\nShe: Yes, please!'

"""Me: Hi, there! 
She: Yes, please!"""

#BasicInputOutput

input("Give me your country name: ")

print("hellow world!")

print('Name:BD\nP:200M')

#@title Concatenation

"spam"+"eggs"

"2" + "2"

"take"*3

'17'*77

'17'*(2+4)

'12'+'tough'

3*'take'

#@title String Formating

msg = "The marks are Math:{1}, English:{0},physics{0}".format(90,100)

print(msg)

msg = "if x={x} and y = {y} then x+y ={z}".format(x=20,y=30,z=20+30)
print(msg)

print(" hello ".join(["apple", "orange", "pineapple"]))

print("hellow you".replace("you","World"))

print("hellow you".endswith("you"))

print("This is a sentance".upper())

print("a,e,i,o,u".split(","))

#@title টাইপ কনভার্সন

int("123")

int(12.3)

float('123.456')

float('123')

int("123.456")

str(123)

print("float = " +str(10.5))

